backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

media_folder: static/img
public_folder: /img

collections:
  - name: "blog"
    label: "ブログ"
    folder: "src/pages/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
      - {label: "タイトル名", name: "title", widget: "string"}
      - {label: "公開日", name: "date", widget: "datetime"}
      - {label: "説明", name: "description", widget: "text"}
      - {label: "特定投稿", name: "featuredpost", widget: "boolean"}
      - {label: "特定画像", name: "featuredimage", widget: image}
      - {label: "ボディ", name: "body", widget: "markdown"}
      - {label: "タグ", name: "tags", widget: "list"}

  - name: "pages"
    label: "ページ"
    files:
      - file: "src/pages/index.md"
        label: "ランディングページ"
        name: "index"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "index-page"}
          - {label: タイトル名, name: title, widget: string}
          - {label: 画像, name: image, widget: image}
          - {label: ヘッダー, name: heading, widget: string}
          - {label: サブヘッダー, name: subheading, widget: string}
          - {label: メインピッチ, name: mainpitch, widget: object, fields: [{label: タイトル名, name: title, widget: string}, {label: 説明, name: description, widget: text}]}
          - {label: 説明, name: description, widget: string}
          - {label: 紹介, name: intro, widget: object, fields: [{label: ヘッダー, name: heading, widget: string}, {label: 説明, name: description, widget: text}, {label: 推薦, name: blurbs, widget: list, fields: [{label: 画像, name: image, widget: image}, {label: テキスト, name: text, widget: text}]}]}
          - {label: メイン, name: main, widget: object, fields: [{label: ヘッダー, name: heading, widget: string}, {label: 説明, name: description, widget: text}, {label: 画像1, name: image1, widget: object, fields: [{label: 画像, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: 画像2, name: image2, widget: object, fields: [{label: 画像, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: 画像3, name: image3, widget: object, fields: [{label: 画像, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}]}
      - file: "src/pages/about/index.md"
        label: "KS Blogについて"
        name: "about"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page"}
          - {label: "タイトル名", name: "title", widget: "string"}
          - {label: "ボディ", name: "body", widget: "markdown"}
      - file: "src/pages/products/index.md"
        label: "商品・サービスページ"
        name: "products"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "product-page"}
          - {label: タイトル名, name: title, widget: string}
          - {label: 画像, name: image, widget: image}
          - {label: ヘッダー, name: heading, widget: string}
          - {label: 説明, name: description, widget: string}
          - {label: 紹介, name: intro, widget: object, fields: [{label: ヘッダー, name: heading, widget: string}, {label: 説明, name: description, widget: text}, {label: 推薦, name: blurbs, widget: list, fields: [{label: 画像, name: image, widget: image}, {label: テキスト, name: text, widget: text}]}]}
          - {label: メイン, name: main, widget: object, fields: [{label: ヘッダー, name: heading, widget: string}, {label: 説明, name: description, widget: text}, {label: 画像1, name: image1, widget: object, fields: [{label: 画像, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: 画像2, name: image2, widget: object, fields: [{label: 画像, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: 画像3, name: image3, widget: object, fields: [{label: 画像, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}]}
          - {label: お客さまの声, name: testimonials, widget: list, fields: [{label: Quote, name: quote, widget: string}, {label: 著者, name: author, widget: string}]}
          - {label: フル画像, name: full_image, widget: image}
          - {label: 料金, name: pricing, widget: object, fields: [{label: ヘッダー, name: heading, widget: string}, {label: 説明, name: description, widget: string}, {label: プラン, name: plans, widget: list, fields: [{label: プラン, name: plan, widget: string}, {label: 料金, name: price, widget: string}, {label: 説明, name: description, widget: string}, {label: 商品, name: items, widget: list}]}]}
